services:
  database:
    container_name: comics-database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: comics_user
      POSTGRES_PASSWORD: comics_password
      POSTGRES_DB: comics_database
    ports:
      - '5432:5432'
  application:
    container_name: comics-application
    build: ./
    image: itiszakk/comics-api:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database